Workstatic/Models/JobPosting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Workstatic.Models
{
    public class JobPosting 
    {
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public int Id { get; set; }
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public string JobTitle { get; set; }
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public int Salary { get; set; }

        [Required(ErrorMessage = "Standort ist erforderlich")]
        public string JobLocation { get; set; }
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public DateTime StartDate { get; set; }
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public string CompanyName { get; set; }
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public string ContactPhone { get; set; }
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public string ContactMail { get; set; }
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public string ContactWebsite { get; set; }
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public byte[] CompanyImage { get; set; }
        [Required(ErrorMessage = "Standort ist erforderlich")]
        public string OwnerUsername { get; set; }
        
    }
}

Workstatic/Controllers/JobPostingController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Workstatic.Data;
using Workstatic.Models;


namespace Workstatic.Controllers
{
    [Authorize]
    public class JobPostingController : Controller
    {
        private readonly ApplicationDbContext _context;
        public JobPostingController(ApplicationDbContext context)
        {
           _context = context; 
        }
        public IActionResult Index() 
        {

            if (User.IsInRole("Admin"))
            {
                var allPostings = _context.JobPostings.ToList();
                return View(allPostings);
            }

            var jobPostingsFromDb = _context.JobPostings.Where(x => x.OwnerUsername == User.Identity.Name).ToList();
            //benutzer Name x. Wenn der Nutzer Name von X (was für JobPosting steht)
            //der Benutzername ist, mit dem wir gerade eingeloggt sind   
            return View(jobPostingsFromDb);

        }
        
        public IActionResult CreateEditJobPosting(int id)
        {
            if (id != 0)
            {
                var jobPostingFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == id);

                if ((jobPostingFromDb.OwnerUsername != User.Identity.Name) && !User.IsInRole("Admin"))
                {
                    return Unauthorized();
                }

                if (jobPostingFromDb != null)
                {
                    return View(jobPostingFromDb);
                }
                else
                {
                    return NotFound();
                }
            }
            return View();
        }

        public IActionResult CreateEditJob(JobPosting jobPosting, IFormFile file) 
        {
            jobPosting.OwnerUsername = User.Identity.Name;

            if (file != null)
            {
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    var bytes = ms.ToArray();
                    jobPosting.CompanyImage = bytes;
                }
            }

            if (jobPosting.Id == 0)
            {
                // Add new job if it's not editing. 
                _context.JobPostings.Add(jobPosting);
            }
            else
            {
                var jobFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == jobPosting.Id);

                if (jobFromDb == null)
                    return NotFound();
                

                jobFromDb.CompanyImage = jobPosting.CompanyImage;
                jobFromDb.CompanyName = (jobPosting.CompanyName == null) ? "Keinen Name vorhanden." : jobPosting.CompanyName;
                jobFromDb.ContactMail = (jobPosting.ContactMail == null) ? "Keine Email vorhanden." : jobPosting.ContactMail;
                jobFromDb.ContactPhone = (jobPosting.ContactPhone==null) ? "Keine Tel. vorhanden." : jobPosting.ContactPhone;
                jobFromDb.ContactWebsite = (jobPosting.ContactWebsite == null) ? "Keine Website vorhanden." : jobPosting.ContactWebsite;
                jobFromDb.Description = (jobPosting.Description == null) ? "Keine Description vorhanden." : jobPosting.Description;
                jobFromDb.JobLocation = (jobPosting.JobLocation == null) ? "Keine JobLocation vorhanden." : jobPosting.JobLocation;
                jobFromDb.JobTitle = (jobPosting.JobTitle == null) ? "Keinen JobTitle vorhanden." : jobPosting.JobTitle;
                jobFromDb.Salary = jobPosting.Salary;    
                jobFromDb.StartDate = jobPosting.StartDate;
                //jobFromDb.OwnerUsername = (jobPosting.OwnerUsername == null) ? "Keinen OwnerUsername vorhanden." : jobPosting.OwnerUsername;
            }

            _context.SaveChanges();

            // todo: write jobposting to db 
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteJobPostingById(int id)
        {
            if (id == 0)
                return BadRequest();

            var jobPostingFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == id);

            if (jobPostingFromDb == null)
                return NotFound();

            _context.JobPostings.Remove(jobPostingFromDb);
            _context.SaveChanges();

            return Ok();
            
        }
    }

}

Workstatic/Views/JobPosting/CreateEditJobPosting.cshtml
@model Workstatic.Models.JobPosting;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	ViewData["Title"] = "Erstellen oder Bearbeiten";
}


<form asp-controller="JobPosting" asp-action="CreateEditJob" enctype="multipart/form-data">
	<div class="card">
		<div class="card-header">
			<h5>Inserat bearbeiten</h5>
		</div>

		<div class="card-body">

			<input hidden asp-for="Id" />

			<div class="row form-group">
				<div class="col">
					<input class="form-control" asp-for="JobTitle" type="text"  required placeholder="Bitte trage eine Jobbezeichnung ein" />
				</div>
				<div class="col">
					<input class="form-control" asp-for="JobLocation" type="text" required placeholder="Bitte trage eine Ort ein" />
				</div>
			</div>

			<div class="row form-group">
				<div class="col">
					<textarea rows="6" class="form-control" asp-for="Description" required type="text" placeholder="Bitte trage eine ausführliche Beschreibung ein ein">
				</textarea>
				</div>
			</div>

			<div class="row form-group">
				<div class="col">
					<input class="form-control" asp-for="Salary" type="number" required placeholder="Wie viel Jahresgehalt zahlt ihr?" />
				</div>
			</div>

			<div class="row form-group">
				<div class="col">
					Wann startet der Job?
					<input class="form-control" asp-for="StartDate" type="date" required placeholder="Wann startet der Job?" />
				</div>
			</div>
		

		<hr />

		<div class="row form-group">
			<div class="col">
				<input class="form-control" asp-for="CompanyName" type="text" required placeholder="Wie heißt deine Firma?" />
			</div>
			<div class="col">
				<input class="form-control" asp-for="ContactWebsite" type="url" required placeholder="Wie lautet die Webadresse?" />
			</div>
		</div>

		<div class="row form-group">
			<div class="col">
				<input class="form-control" asp-for="ContactPhone" type="tel" required placeholder="Telefonnummer" />
			</div>
			<div class="col">
				<input class="form-control" asp-for="ContactMail" type="email" required placeholder="E-Mail Adresse" />
			</div>
		</div>

			<div class="row form-group">
				<div class="col">
					<label>Bild</label>
					<input class="form-control-file" name="file" type="file" required/>
				</div>
			</div>
		</div>

		<div class="card-footer">
			<button class="btn btn-primary" type="submit">Speichern</button>
		</div>
	</div>


</form>

Workstatic/Views/JobPosting/Index.cshtml
@model List<JobPosting>

@{
	ViewData["Title"] = "Deine Inserate";
}

<a class="btn btn-primary" asp-controller="JobPosting" asp-action="CreateEditJobPosting">Neues Inserat anlegen</a>
<hr />

<table id="jobPostingTable" class="table table-bordered table-striped table-hover">
	<thead class="thead-dark">
		<tr>
			<th>Job Title</th>
			<th>Ort</th>
			<th>Firmenname</th>
			<th>Aktionen</th>
		</tr>
	</thead>

	<tbody>
		@{
			foreach (JobPosting jobPosting in Model)
			{
					<tr>
						<td>@jobPosting.JobTitle</td>
						<td>@jobPosting.JobLocation</td>
						<td>@jobPosting.CompanyName</td>
						<td> 
							<a asp-route-id="@jobPosting.Id" asp-controller="JobPosting" asp-action="CreateEditJobPosting" class="btn btn-warning">Edit</a>
							<button onclick=" onClickedDeleteBtn(@jobPosting.Id)" class="btn btn-danger">Delete</button>
					 	</td>
					</tr>
			}
		}
	</tbody>
</table>

@section Scripts {
			<script> // for DataTable 
				$(document).ready( function () {
				$('#jobPostingTable').DataTable();
				} );

				// for Delete-Dialog
				function onClickedDeleteBtn(id){
									Swal.fire({
					title: 'Möchtest du das Inserat wirklich löschen?',
					icon: 'error',
					showCloseButton: true,
					focusConfirm: false,
					confirmButtonText:
						'Ja, löschen!',
				}).then((result) => {
					if (result.isConfirmed) {

						// Backend call to delete job posting by id
						$.ajax({
							type: "POST",
							url: "@Url.Action("DeleteJobPostingById")",
							data: { id: id },
							success: function (msg) {
								Swal.fire('Wurde gelöscht!', '', 'success').then((result) => {
									location.reload();                                
								});
							},
							error: function (msg) {
								Swal.fire('Ups, etwas ist schief gelaufen!', '', 'error')
							}
						});
					}
				})
			}	

		</script>
}